name: sorted_storage
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.0.0
  eva_icons_flutter: ^3.0.0
  firebase_auth: ^1.4.1
  firebase_core: ^1.3.0
  firebase_crashlytics: ^2.0.7
  flutter_bloc: ^7.0.0
  google_sign_in: ^5.0.4
  googleapis: ^3.0.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  intl: ^0.17.0
  url_launcher: ^6.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.1
  build_runner: ^2.0.4
  import_sorter: ^4.6.0
  mocktail: ^0.1.4
  very_good_analysis: ^2.1.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Bold.ttf
          weight: 700
