enum LocalStoriesType {
  initial_state,
  picked_image,
  create_sub_story,
  delete_sub_story,
  edit_timestamp,
  edit_description,
  edit_emoji,
  edit_title,
  delete_image,
  add_image,
  cancel_story,
  edit_story,
  syncing_story_end,
}
